from ..base import BaseModelConfig as BaseModelConfig
from _typeshed import Incomplete
from dataclasses import dataclass, field

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig = field(default_factory=Incomplete)
    vision_config: VisionConfig = field(default_factory=Incomplete)
    model_type: str = ...
    image_feature_dropout: float = ...
    image_pooling_h: int = ...
    image_pooling_w: int = ...
    image_pooling_2d: str = ...
    image_projector: str = ...
    eos_token_id: list[int] | None = ...

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str = ...
    max_position_embeddings: int = ...
    d_model: int = ...
    n_heads: int = ...
    n_kv_heads: int = ...
    n_layers: int = ...
    mlp_ratio: int = ...
    max_sequence_length: int = ...
    act_output_multiplier: int = ...
    mlp_hidden_size: int = ...
    vocab_size: int = ...
    embedding_size: int | None = ...
    additional_vocab_size: int | None = ...
    attention_dropout: float = ...
    residual_dropout: float = ...
    embedding_dropout: float = ...
    layer_norm_eps: float = ...
    initializer_range: float = ...
    pad_token_id: int = ...
    rope: bool = ...
    rope_theta: float = ...
    weight_tying: bool = ...
    rope_full_precision: bool = ...
    rope_impl: str = ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str = ...
    num_channels: int = ...
    image_default_input_size: tuple[int, int] = ...
    image_patch_size: int = ...
    image_pos_patch_size: int = ...
    hidden_size: int = ...
    image_emb_dim: int = ...
    image_num_heads: int = ...
    image_num_key_value_heads: int = ...
    image_num_layers: int = ...
    image_head_dim: int = ...
    image_mlp_dim: int = ...
    image_mlp_activations: str = ...
    image_dropout_rate: float = ...
    image_num_pos: int = ...
    image_norm_eps: float = ...
    attention_dropout: float = ...
    residual_dropout: float = ...
    initializer_range: float = ...
    d_model: int = ...
    image_pooling_h: int = ...
    image_pooling_w: int = ...
    vit_layers: list[int] | None = field(default_factory=Incomplete)
    image_pooling_2d: str = ...
    image_padding_embed: str = ...
    intermediate_size: int | None = ...
    def __post_init__(self) -> None: ...
    @property
    def image_num_patch(self): ...
    @property
    def llm_patches_per_crop(self): ...
