from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str = ...
    hidden_size: int = ...
    num_hidden_layers: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    num_key_value_heads: int = ...
    max_position_embeddings: int = ...
    rope_theta: float = ...
    vocab_size: int = ...
    eos_token_id: int = ...
    initializer_range: float = ...
    norm_eps: float = ...
    use_cache: bool = ...
    use_pos_enc: bool = ...
    block_auto_adjust_ff_dim: bool = ...
    block_dim: int = ...
    block_ff_dim: int = ...
    block_ffn_dim_multiplier: float = ...
    block_mlp_init_scale: float = ...
    block_multiple_of: int = ...
    block_norm_eps: float = ...
    block_out_init_scale: float = ...
    block_use_swiglu: bool = ...
    block_use_xavier_init: bool = ...
    conv_L_cache: int = ...
    conv_bias: bool = ...
    conv_dim: int = ...
    conv_dim_out: int = ...
    conv_use_xavier_init: bool = ...
    layer_types: list[str] = ...
    num_heads: int = ...
    full_attn_idxs: list[int] = ...
    def __post_init__(self) -> None: ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    num_hidden_layers: int = ...
    num_attention_heads: int = ...
    num_channels: int = ...
    image_size: int = ...
    patch_size: int = ...
    num_patches: int = ...
    attention_dropout: float = ...
    layer_norm_eps: float = ...
    hidden_act: str = ...
    vision_use_head: bool = ...
    num_positions: int = ...
    spatial_shapes: list[tuple[int, int]] = ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str = ...
    do_image_splitting: bool = ...
    downsample_factor: int = ...
    encoder_patch_size: int = ...
    image_token_index: int = ...
    max_image_tokens: int = ...
    max_num_patches: int = ...
    max_pixels_tolerance: float = ...
    max_tiles: int = ...
    min_image_tokens: int = ...
    min_tiles: int = ...
    tile_size: int = ...
    use_image_special_tokens: bool = ...
    use_thumbnail: bool = ...
    vision_feature_layer: int = ...
    projector_bias: bool = ...
    projector_hidden_act: str = ...
    projector_hidden_size: int = ...
    eos_token_id: int = ...
