import mlx.core as mx
import mlx.nn as nn
from .config import ModelConfig as ModelConfig
from .language import LanguageModel as LanguageModel
from .vision import VisionModel as VisionModel
from _typeshed import Incomplete

class Lfm2VlMultiModalProjector(nn.Module):
    layer_norm: Incomplete
    linear_1: Incomplete
    linear_2: Incomplete
    def __init__(self, config: ModelConfig) -> None: ...
    def __call__(self, x): ...

class PixelUnshuffleBlock(nn.Module):
    factor: Incomplete
    def __init__(self, factor: int) -> None: ...
    def __call__(self, x): ...

def masked_scatter(final_embedding: mx.array, image_mask_expanded: mx.array, scaled_image_features: mx.array): ...

class Model(nn.Module):
    model_type: Incomplete
    config: Incomplete
    vision_tower: Incomplete
    pixel_unshuffle: Incomplete
    multi_modal_projector: Incomplete
    language_model: Incomplete
    def __init__(self, config: ModelConfig) -> None: ...
    def get_input_embeddings(self, input_ids: mx.array | None = None, pixel_values: mx.array | None = None, spatial_shapes: mx.array | None = None, pixel_attention_mask: mx.array | None = None): ...
    @staticmethod
    def merge_input_ids_with_image_features(image_features, inputs_embeds, input_ids, image_token_index): ...
    @property
    def layers(self): ...
    def __call__(self, input_ids: mx.array, pixel_values: mx.array, mask: mx.array, cache=None, **kwargs): ...
    def sanitize(self, weights): ...
