from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str
    hidden_size: int
    intermediate_size: int
    num_hidden_layers: int
    num_attention_heads: int
    image_size: int
    patch_size: int
    layer_norm_eps: float = ...
    num_channels: int = ...

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    hidden_size: int
    num_hidden_layers: int
    intermediate_size: int
    num_attention_heads: int
    rms_norm_eps: float
    vocab_size: int
    num_key_value_heads: int
    rope_theta: float = ...
    rope_traditional: bool = ...
    max_position_embeddings: int = ...
    tie_word_embeddings: bool = ...
    def __post_init__(self) -> None: ...

@dataclass
class PerceiverConfig(BaseModelConfig):
    model_type: str
    num_key_value_heads: int = ...
    resampler_depth: int = ...
    resampler_head_dim: int = ...
    resampler_n_heads: int = ...
    resampler_n_latents: int = ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    perceiver_config: PerceiverConfig
    model_type: str
    ignore_index: int = ...
    image_token_id: int = ...
    vocab_size: int = ...
    image_token_index: int | None = ...
    eos_token_id: list[int] | None = ...
    def __post_init__(self) -> None: ...
