from ..base import BaseModelConfig as BaseModelConfig
from _typeshed import Incomplete
from dataclasses import dataclass, field

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    vocab_size: int
    hidden_size: int
    intermediate_size: int
    max_position_embeddings: int
    moe_intermediate_size: int
    norm_topk_prob: bool
    num_attention_heads: int
    n_group: int
    head_dim: int
    topk_group: int
    n_shared_experts: int
    n_routed_experts: int
    routed_scaling_factor: float
    num_experts_per_tok: int
    first_k_dense_replace: int
    num_hidden_layers: int
    num_key_value_heads: int
    rms_norm_eps: float
    rope_theta: float
    use_qk_norm: bool
    attention_bias: bool
    partial_rotary_factor: float
    rope_scaling: dict = field(default_factory=Incomplete)
    tie_word_embeddings: bool = ...
    scoring_func: str = ...
    topk_method: str = ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str
    depth: int
    hidden_size: int
    intermediate_size: int
    num_heads: int
    patch_size: int
    window_size: int = ...
    image_size: int = ...
    in_channels: int = ...
    rms_norm_eps: float = ...
    attention_bias: bool = ...
    attention_dropout: float = ...
    hidden_act: str = ...
    initializer_range: float = ...
    out_hidden_size: int = ...
    spatial_merge_size: int = ...
    temporal_patch_size: int = ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    vocab_size: int = ...
    ignore_index: int = ...
    image_token_index: int = ...
    image_token_id: int = ...
    video_token_index: int = ...
    video_token_id: int = ...
    vision_start_token_id: int = ...
    vision_end_token_id: int = ...
    hidden_size: int = ...
    pad_token_id: int = ...
    eos_token_id: list[int] | None = ...
    def __post_init__(self) -> None: ...
