from ..base import BaseModelConfig as BaseModelConfig
from _typeshed import Incomplete
from dataclasses import dataclass, field

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str = ...
    vocab_size: int = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    num_hidden_layers: int = ...
    num_attention_heads: int = ...
    num_key_value_heads: int = ...
    hidden_act: str = ...
    max_position_embeddings: int = ...
    initializer_range: float = ...
    rms_norm_eps: float = ...
    tie_word_embeddings: bool = ...
    rope_theta: float = ...
    rope_traditional: bool = ...
    rope_scaling: dict[str, float | str] | None = ...
    cross_attention_layers: list[int] = field(default_factory=Incomplete)
    def __post_init__(self) -> None: ...

@dataclass
class VisionConfig(BaseModelConfig):
    image_size: int = ...
    patch_size: int = ...
    num_channels: int = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    num_hidden_layers: int = ...
    num_attention_heads: int = ...
    max_num_tiles: int = ...
    max_aspect_ratio_id: int = ...
    num_global_layers: int = ...
    norm_eps: float = ...
    attention_dropout: float = ...
    hidden_dropout: float = ...
    vision_output_dim: int = ...
    intermediate_layers_indices: list[int] = field(default_factory=Incomplete)
    supported_aspect_ratios: tuple[list[int]] = ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    ignore_index: int = ...
    image_token_index: int = ...
    vision_feature_select_strategy: str = ...
    vision_feature_layer: int = ...
    vocab_size: int = ...
    eos_token_id: list[int] | None = ...
