from ..base import BaseModelConfig as BaseModelConfig
from _typeshed import Incomplete
from dataclasses import dataclass, field
from types import SimpleNamespace as SimpleNamespace

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig = field(default_factory=Incomplete)
    vision_config: VisionConfig = field(default_factory=Incomplete)
    model_type: str = ...
    vocab_size: int = ...
    num_hidden_layers: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    rms_norm_eps: float = ...
    ignore_index: int = ...
    image_token_index: int = ...
    hidden_size: int = ...
    pad_token_id: int = ...
    num_key_value_heads: int = ...
    rope_theta: float = ...
    rope_traditional: bool = ...
    rope_scaling: dict[str, float | str] | None = ...
    max_position_embeddings: int = ...
    original_max_position_embeddings: int = ...
    eos_token_id: list[int] | None = ...

@dataclass
class TextConfig(BaseModelConfig):
    max_position_embeddings: int = ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str = ...
    num_hidden_layers: int = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    image_size: int = ...
    patch_size: int = ...
    projection_dim: int = ...
    vocab_size: int = ...
    num_channels: int = ...
    layer_norm_eps: float = ...
    image_dim_out: int = ...
    model_name: str = ...
    name: str = ...
    num_img_tokens: int = ...
