"""
This type stub file was generated by pyright.
"""

import mlx.core as mx
from abc import abstractmethod
from dataclasses import dataclass
from typing import Dict, List, Optional
from transformers.image_processing_utils import BaseImageProcessor as ImageProcessor

@dataclass
class LanguageModelOutput:
    logits: mx.array
    cross_attention_states: Optional[List[mx.array]] = ...
    encoder_outputs: Optional[List[mx.array]] = ...


def expand2square(pil_img, background_color): # -> Image:
    ...

class BaseImageProcessor(ImageProcessor):
    def __init__(self, image_mean=..., image_std=..., size=..., crop_size: Dict[str, int] = ..., resample=..., rescale_factor=..., data_format=...) -> None:
        ...
    
    @abstractmethod
    def preprocess(self, images): # -> None:
        ...
    


def visualize_attention_mask(mask): # -> None:
    """Visualize attention mask with symbols for better readability."""
    ...

def check_activation_stats(name, tensor): # -> None:
    """Helper function to check for anomalies and log stats."""
    ...

def pixel_shuffle(input_tensor, shuffle_ratio):
    ...

def interpolate(pos_embed, size, mode=..., align_corners=...):
    """
    MLX implementation of PyTorch's F.interpolate with bicubic mode

    Args:
        pos_embed: MLX array with shape [B, C, H_src, W_src] or [C, H_src, W_src]
        size: Tuple (H_dst, W_dst) - target size
        align_corners: Boolean - whether to align corners

    Returns:
        Interpolated array with shape [B, C, H_dst, W_dst] or [C, H_dst, W_dst]
    """
    ...

