"""
This type stub file was generated by pyright.
"""

class SimpleKVCache:
    """A simple key-value cache for transformer attention layers.

    Stores and concatenates key/value tensors along sequence dimension.
    """
    def __init__(self) -> None:
        ...
    
    def update_and_fetch(self, keys, values): # -> tuple[Any, Any]:
        """Update cache with new key/value tensors and return full cache.

        Args:
            keys: New key tensor to add [batch, heads, seq_len, head_dim]
            values: New value tensor to add [batch, heads, seq_len, head_dim]

        Returns:
            Tuple of (cached_keys, cached_values) containing full cache history
        """
        ...
    
    def fetch(self): # -> tuple[Any | None, Any | None]:
        ...
    
    def update(self, keys, values): # -> None:
        """Update cache with new key/value tensors without returning.

        Args:
            keys: New key tensor to store
            values: New value tensor to store
        """
        ...
    


