def nearest_interpolate(x, size=None, scale_factor=None): ...
def bicubic_interpolate(x, size=None, scale_factor=None, align_corners: bool = False): ...
def grid_sample(x, grid): ...
def get_optimal_threadgroup(out_w, out_h): ...
