from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str
    hidden_size: int = ...
    num_attention_heads: int = ...
    patch_size: int = ...
    num_hidden_layers: int = ...
    intermediate_size: int = ...
    image_size: int = ...
    num_channels: int = ...
    layer_norm_eps: float = ...
    drop_path_rate: float = ...
    qkv_bias: bool = ...
    qk_normalization: bool = ...
    norm_type: str = ...

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    hidden_size: int
    num_hidden_layers: int
    intermediate_size: int
    num_attention_heads: int
    rms_norm_eps: float
    vocab_size: int
    max_window_layers: int
    hidden_act: str
    num_key_value_heads: int | None = ...
    max_position_embeddings: int | None = ...
    rope_theta: float = ...
    rope_traditional: bool = ...
    rope_scaling: dict[str, float | str] | None = ...
    tie_word_embeddings: bool = ...
    sliding_window: int = ...
    use_sliding_window: bool = ...
    use_cache: bool = ...
    def __post_init__(self) -> None: ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    ignore_index: int = ...
    image_token_index: int = ...
    video_token_index: int = ...
    vision_feature_select_strategy: str = ...
    vision_feature_layer: int = ...
    vocab_size: int = ...
    downsample_ratio: float = ...
    eos_token_id: list[int] | None = ...
