from _typeshed import Incomplete
from mlx_vlm import load as load
from mlx_vlm.generate import generate_step as generate_step
from mlx_vlm.prompt_utils import get_message_json as get_message_json
from mlx_vlm.utils import load_image as load_image

class MLXVisionChat:
    console: Incomplete
    verbose: Incomplete
    temperature: Incomplete
    max_tokens: Incomplete
    history: list[dict]
    current_image: Incomplete
    def __init__(self, model_path: str = 'mlx-community/idefics2-8b-chatty-4bit', temperature: float = 0.7, max_tokens: int = 1000, verbose: bool = False) -> None: ...
    def print_help(self) -> None: ...
    def process_image(self, image_path: str) -> bool: ...
    def add_to_history(self, role: str, text: str) -> None: ...
    def generate_response(self) -> str: ...
    def handle_command(self, command: str, args: str) -> bool: ...
    def chat_loop(self) -> None: ...

def main() -> None: ...
