import argparse
import mlx.nn as nn
from .utils import MODEL_CONVERSION_DTYPES as MODEL_CONVERSION_DTYPES, fetch_from_hub as fetch_from_hub, get_model_path as get_model_path, save_config as save_config, save_weights as save_weights, skip_multimodal_module as skip_multimodal_module, upload_to_hub as upload_to_hub
from _typeshed import Incomplete
from typing import Callable

QUANT_RECIPES: Incomplete

def mixed_quant_predicate_builder(recipe: str, model: nn.Module) -> Callable[[str, nn.Module], bool | dict]: ...
def convert(hf_path: str, mlx_path: str = 'mlx_model', quantize: bool = False, q_group_size: int = 64, q_bits: int = 4, dtype: str | None = None, upload_repo: str = None, revision: str | None = None, dequantize: bool = False, trust_remote_code: bool = True, quant_predicate: str | None = None): ...
def configure_parser() -> argparse.ArgumentParser: ...
def main() -> None: ...
