from argparse import Namespace
from pathlib import Path
from typing import Any

from mlx import nn
from transformers import PreTrainedTokenizer, PreTrainedTokenizerFast

DEFAULT_MODEL_PATH: str = ...
DEFAULT_IMAGE: str | None = ...
DEFAULT_PROMPT: str = ...
DEFAULT_MAX_TOKENS: int = ...
DEFAULT_TEMPERATURE: float = ...
DEFAULT_TOP_P: float = ...
DEFAULT_SEED: int = ...

def parse_arguments() -> Namespace:
    ...

def get_model_and_processors(
    model_path: str | Path,
    adapter_path: str | Path | None = None,
) -> tuple[nn.Module, PreTrainedTokenizer | PreTrainedTokenizerFast, dict[str, Any]]:
    ...

def main() -> None:
    ...
