"""
This type stub file was generated by pyright.
"""

def get_message_json(model_name, prompt, role=..., skip_image_token=..., num_images=..., **kwargs): # -> dict[str, str | list[dict[str, str]] | list[dict[str, str | Any]]] | dict[str, str | Any] | dict[str, str | list[dict[str, str | Any]]]:
    """
    Get the appropriate JSON message based on the specified model.

    Args:
        model_name (str): The model for which to generate the message.
        prompt (str): The text prompt to be included in the message.
        role (str): The role of the message (default: "user").
        skip_image_token (bool): Whether to skip adding image tokens (default: False).
        num_images (int): Number of image tokens to add (default: 1).

    Returns:
        dict: A dictionary representing the JSON message for the specified model.
    """
    ...

def get_chat_template(processor, messages, add_generation_prompt, tokenize=..., **kwargs):
    ...

def apply_chat_template(processor, config, prompt, add_generation_prompt=..., return_messages=..., num_images=..., **kwargs): # -> list[dict[str, str | list[dict[str, str]] | list[dict[str, str | Any]]] | str | dict[str, str | list[dict[str, str | Any]]] | dict[str, str] | dict[str, Any | str | list[dict[str, str]] | list[dict[str, str | Any]]] | dict[str, str | Any] | dict[str, Any | list[dict[str, str | Any]]] | Any] | dict[str, str | list[dict[str, str]] | list[dict[str, str | Any]]] | str | dict[str, str | list[dict[str, str | Any]]] | dict[str, str] | dict[str, Any | str | list[dict[str, str]] | list[dict[str, str | Any]]] | dict[str, str | Any] | dict[str, Any | list[dict[str, str | Any]]]:
    ...

