from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    hidden_size: int = ...
    num_hidden_layers: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    rms_norm_eps: float = ...
    vocab_size: int = ...
    num_key_value_heads: int = ...
    rope_theta: float = ...
    rope_traditional: bool = ...
    rope_scaling: dict[str, float | str] | None = ...
    max_position_embeddings: int = ...
    tie_word_embeddings: bool = ...
    def __post_init__(self) -> None: ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str
    num_hidden_layers: int = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    image_size: int = ...
    patch_size: int = ...
    projection_dim: int = ...
    vocab_size: int = ...
    num_channels: int = ...
    layer_norm_eps: float = ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    ignore_index: int = ...
    image_token_index: int = ...
    vision_feature_select_strategy: str = ...
    vision_feature_layer: int = ...
    vocab_size: int = ...
    eos_token_id: list[int] | None = ...
