from ..base import BaseModelConfig as BaseModelConfig
from _typeshed import Incomplete
from dataclasses import dataclass, field

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str = ...
    in_chans: int = ...
    num_classes: int = ...
    depths: list[int] = field(default_factory=Incomplete)
    dim_embed: list[int] = field(default_factory=Incomplete)
    num_heads: list[int] = field(default_factory=Incomplete)
    num_groups: list[int] = field(default_factory=Incomplete)
    window_size: int = ...
    mlp_ratio: float = ...
    drop_path_rate: float = ...
    patch_size: list[int] = field(default_factory=Incomplete)
    patch_stride: list[int] = field(default_factory=Incomplete)
    patch_padding: list[int] = field(default_factory=Incomplete)
    patch_prenorm: list[bool] = field(default_factory=Incomplete)
    qkv_bias: bool = ...
    conv_at_attn: bool = ...
    conv_at_ffn: bool = ...
    hidden_size: int = ...
    image_size: tuple[int, int] = ...

@dataclass
class TextConfig(BaseModelConfig):
    d_model: int = ...
    model_type: str = ...
    encoder_attention_heads: int = ...
    decoder_attention_heads: int = ...
    encoder_ffn_dim: int = ...
    decoder_ffn_dim: int = ...
    dropout: float = ...
    attention_dropout: float = ...
    activation_dropout: float = ...
    activation_function: str = ...
    init_std: float = ...
    encoder_layerdrop: float = ...
    decoder_layerdrop: float = ...
    scale_embedding: bool = ...
    use_cache: bool = ...
    max_position_embeddings: int = ...
    vocab_size: int = ...
    pad_token_id: int = ...
    bos_token_id: int = ...
    eos_token_id: int = ...
    encoder_layers: int = ...
    decoder_layers: int = ...

@dataclass
class ModelConfig(BaseModelConfig):
    vision_config: VisionConfig
    text_config: TextConfig
    model_type: str = ...
    vocab_size: int = ...
    max_position_embeddings: int = ...
    pad_token_id: int = ...
    bos_token_id: int = ...
    eos_token_id: int = ...
    image_token_index: int = ...
    image_feature_source: list[str] = field(default_factory=Incomplete)
    visual_temporal_embedding: dict | None = field(default_factory=Incomplete)
    image_pos_embed: dict | None = field(default_factory=Incomplete)
