from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    hidden_size: int
    intermediate_size: int
    num_attention_heads: int
    rms_norm_eps: float
    vocab_size: int
    num_key_value_heads: int
    rope_theta: float = ...
    num_hidden_layers: int = ...
    rope_traditional: bool = ...
    rope_scaling: dict | None = ...
    tie_word_embeddings: bool = ...
    head_dim: int = ...
    hidden_act: str = ...
    intermediate_size_mlp: int = ...
    max_position_embeddings: int = ...
    num_experts_per_tok: int = ...
    num_local_experts: int = ...
    attention_dropout: float = ...
    use_qk_norm: bool = ...
    bos_token_id: int = ...
    eos_token_id: list = ...
    pad_token_id: int = ...
    attention_chunk_size: int = ...
    attention_bias: bool = ...
    interleave_moe_layer_step: int = ...
    no_rope_layers: list = ...
    output_router_logits: bool = ...
    router_aux_loss_coef: float = ...
    router_jitter_noise: float = ...
    attn_temperature_tuning: int = ...
    floor_scale: float = ...
    attn_scale: float = ...
    moe_layers: list = ...
    def __post_init__(self) -> None: ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str
    hidden_size: int
    image_size: int
    initializer_range: float
    intermediate_size: int
    norm_eps: float
    num_attention_heads: int
    num_channels: int
    num_hidden_layers: int
    patch_size: int
    pixel_shuffle_ratio: float
    projector_dropout: float
    projector_input_dim: int
    projector_output_dim: int
    rope_theta: float
    vision_feature_layer: int
    vision_feature_select_strategy: str
    vision_output_dim: int

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    ignore_index: int = ...
    image_token_id: int = ...
    image_token_index: int | None = ...
    eos_token_id: list[int] | None = ...
    def __post_init__(self) -> None: ...
