import mlx.core as mx
import mlx.nn as nn
from .config import ModelConfig as ModelConfig, TextConfig as TextConfig, VisionConfig as VisionConfig
from .language import LanguageModel as LanguageModel
from .vision import Llama4MultiModalProjector as Llama4MultiModalProjector, VisionModel as VisionModel
from _typeshed import Incomplete
from pathlib import Path as Path

class Model(nn.Module):
    config: Incomplete
    vision_model: Incomplete
    multi_modal_projector: Incomplete
    language_model: Incomplete
    vocab_size: Incomplete
    def __init__(self, config: ModelConfig) -> None: ...
    def set_input_embeddings(self, value) -> None: ...
    def get_output_embeddings(self): ...
    def set_output_embeddings(self, new_embeddings) -> None: ...
    def set_decoder(self, decoder) -> None: ...
    def get_decoder(self): ...
    def get_image_features(self, pixel_values: mx.array, vision_feature_layer: int | list[int], vision_feature_select_strategy: str, **kwargs): ...
    def get_input_embeddings(self, input_ids: mx.array | None = None, pixel_values: mx.array | None = None, **kwargs): ...
    @property
    def layers(self): ...
    def __call__(self, input_ids: mx.array, pixel_values: mx.array, cache=None, **kwargs): ...
