from ..base import BaseModelConfig as BaseModelConfig
from ..pixtral import TextConfig as TextConfig, VisionConfig as VisionConfig
from dataclasses import dataclass

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    ignore_index: int = ...
    image_token_index: int = ...
    vision_feature_select_strategy: str = ...
    vision_feature_layer: int = ...
    vocab_size: int = ...
    spatial_merge_size: int = ...
    multimodal_projector_bias: bool = ...
    eos_token_id: list[int] | None = ...
