"""
This type stub file was generated by pyright.
"""

import mlx.nn as nn
from typing import Union

class LoRaLayer(nn.Module):
    def __init__(self, linear: Union[nn.Linear, nn.QuantizedLinear], rank: int, alpha: float = ..., dropout: float = ...) -> None:
        ...
    
    def __call__(self, x):
        ...
    


def replace_lora_with_linear(model): # -> None:
    ...

