"""
This type stub file was generated by pyright.
"""

import mlx.nn as nn

def get_module_by_name(model, name): # -> Any:
    ...

def set_module_by_name(model, name, new_module): # -> None:
    ...

def get_peft_model(model, linear_layers, rank=..., alpha=..., dropout=..., freeze=..., verbose=...):
    ...

def freeze_model(model): # -> None:
    ...

def find_all_linear_names(model): # -> list[Any]:
    ...

def count_parameters(model): # -> float:
    ...

def print_trainable_parameters(model): # -> None:
    ...

def apply_lora_layers(model: nn.Module, adapter_path: str) -> nn.Module:
    """
    Apply LoRA layers to the model.

    Args:
        model (nn.Module): The neural network model.
        adapter_path (str): Path to the adapter configuration file.

    Returns:
        nn.Module: The updated model with LoRA layers applied.
    """
    ...

