from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class ProjectorConfig(BaseModelConfig):
    cls: str
    model_type: str
    params: dict

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    hidden_size: int = ...
    num_hidden_layers: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    rms_norm_eps: float = ...
    vocab_size: int = ...
    num_key_value_heads: int = ...
    rope_theta: float = ...
    rope_traditional: bool = ...
    rope_scaling: dict[str, float | str] | None = ...
    max_position_embeddings: int = ...
    def __post_init__(self) -> None: ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str
    num_hidden_layers: int = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    image_size: int = ...
    patch_size: int = ...
    num_channels: int = ...
    layer_norm_eps: float = ...
    cls: str = ...
    params: dict = ...
    def __post_init__(self) -> None: ...

@dataclass
class MLPConfig(BaseModelConfig):
    hidden_size: int
    intermediate_size: int

@dataclass
class SAMViTCfg:
    image_size: tuple[int, int] | int = ...
    width: int = ...
    layers: int = ...
    heads: int = ...
    patch_size: int = ...
    window_size: int = ...
    prompt_embed_dim: int = ...
    global_attn_indexes: list[int] | tuple[int] = ...
    downsample_channels: list[int] | tuple[int] = ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    projector_config: ProjectorConfig
    model_type: str
    ignore_index: int = ...
    image_token_index: int = ...
    vision_feature_select_strategy: str = ...
    select_layer: int = ...
    pad_id: int = ...
    num_image_tokens: int = ...
    vocab_size: int = ...
    eos_token_id: list[int] | None = ...
    @classmethod
    def from_dict(cls, params): ...
