from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    hidden_size: int
    num_hidden_layers: int
    intermediate_size: int
    num_attention_heads: int = ...
    head_dim: int = ...
    rms_norm_eps: float = ...
    vocab_size: int = ...
    num_key_value_heads: int = ...
    rope_global_base_freq: float = ...
    rope_local_base_freq: float = ...
    rope_traditional: bool = ...
    query_pre_attn_scalar: float = ...
    sliding_window: int = ...
    rope_scaling: dict[str, float | list[float]] | None = ...
    mm_tokens_per_image: int = ...
    sliding_window_pattern: int = ...
    max_position_embeddings: int = ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str
    num_hidden_layers: int
    hidden_size: int
    intermediate_size: int
    num_attention_heads: int
    patch_size: int
    image_size: int = ...
    num_channels: int = ...
    layer_norm_eps: float = ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    vocab_size: int = ...
    ignore_index: int = ...
    image_token_index: int = ...
    hidden_size: int = ...
    pad_token_id: int = ...
    eos_token_id: list[int] | None = ...
