import dataclasses
from enum import IntEnum

class SeparatorStyle(IntEnum):
    DeepSeek = ...
    DeepSeekV2 = ...
    PLAIN = ...
    ALIGNMENT = ...

@dataclasses.dataclass
class Conversation:
    name: str
    system_template: str = ...
    system_message: str = ...
    roles: list[str] = ...
    messages: list[list[str]] = ...
    offset: int = ...
    sep_style: SeparatorStyle = ...
    sep: str = ...
    sep2: str = ...
    stop_str: str = ...
    stop_token_ids: list[int] = ...
    def get_prompt(self) -> str: ...
    def set_system_message(self, system_message: str): ...
    def append_message(self, role: str, message: str): ...
    def update_last_message(self, message: str): ...
    def reset_message(self) -> None: ...
    def to_gradio_chatbot(self): ...
    def to_openai_api_messages(self): ...
    def copy(self): ...
    def dict(self): ...

conv_templates: dict[str, Conversation]

def register_conv_template(template: Conversation, override: bool = False): ...
def get_conv_template(name: str) -> Conversation: ...
