from ..base import BaseModelConfig as BaseModelConfig
from _typeshed import Incomplete
from dataclasses import dataclass, field

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig = field(default_factory=Incomplete)
    vision_config: VisionConfig = field(default_factory=Incomplete)
    model_type: str = ...
    vocab_size: int = ...
    ignore_index: int = ...
    image_token_index: int = ...
    hidden_size: int = ...
    pad_token_id: int = ...
    eos_token_id: list[int] | None = ...

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str = ...
    hidden_size: int = ...
    num_hidden_layers: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    num_key_value_heads: int = ...
    vocab_size: int = ...
    head_dim: int = ...
    rms_norm_eps: float = ...
    rope_theta: float = ...
    rope_traditional: bool = ...
    attn_logit_softcapping: float | None = ...
    final_logit_softcapping: float | None = ...
    query_pre_attn_scalar: float | None = ...
    max_position_embeddings: int = ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str = ...
    num_hidden_layers: int = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    patch_size: int = ...
    projection_dim: int = ...
    image_size: int = ...
    num_channels: int = ...
    layer_norm_eps: float = ...
