from ..base import BaseModelConfig as BaseModelConfig
from _typeshed import Incomplete
from dataclasses import dataclass, field

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str = ...
    depth: int = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    out_hidden_size: int = ...
    num_heads: int = ...
    image_size: int = ...
    patch_size: int = ...
    vocab_size: int = ...
    mlp_ratio: float = ...
    in_channels: int = ...
    layer_norm_eps: float = ...
    spatial_patch_size: int = ...
    spatial_merge_size: int = ...
    tokens_per_second: int = ...
    temporal_patch_size: int = ...
    window_size: int = ...
    fullatt_block_indexes: list[int] = field(default_factory=Incomplete)

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    hidden_size: int
    num_hidden_layers: int
    intermediate_size: int
    num_attention_heads: int
    rms_norm_eps: float
    vocab_size: int
    num_key_value_heads: int | None = ...
    max_position_embeddings: int | None = ...
    rope_theta: float = ...
    rope_traditional: bool = ...
    rope_scaling: dict[str, float | str] | None = ...
    tie_word_embeddings: bool = ...
    def __post_init__(self) -> None: ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    ignore_index: int = ...
    image_token_id: int = ...
    video_token_id: int = ...
    vision_start_token_id: int = ...
    vision_end_token_id: int = ...
    vision_token_id: int = ...
    vision_feature_select_strategy: str = ...
    vision_feature_layer: int = ...
    vocab_size: int = ...
    eos_token_id: list[int] | None = ...
    @classmethod
    def from_dict(cls, params): ...
