from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str
    hidden_size: int = ...
    head_dim: int = ...
    num_hidden_layers: int = ...
    intermediate_size: int = ...
    num_attention_heads: int = ...
    num_key_value_heads: int = ...
    rope_theta: float = ...
    vocab_size: int = ...
    layer_norm_eps: float = ...
    logit_scale: float = ...
    attention_bias: bool = ...
    layer_norm_bias: bool = ...
    sliding_window: int = ...
    sliding_window_pattern: int = ...
    max_position_embeddings: int = ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str
    hidden_size: int
    num_attention_heads: int
    patch_size: int
    num_hidden_layers: int = ...
    intermediate_size: int = ...
    image_size: int = ...
    num_channels: int = ...
    layer_norm_eps: float = ...

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    image_token_index: int = ...
    max_splits_per_img: int = ...
    downsample_factor: int = ...
    alignment_intermediate_size: int = ...
    adapter_layer_norm_eps: float = ...
    vision_feature_layer: int = ...
    vision_feature_select_strategy: str = ...
    eos_token_id: list[int] | None = ...
