def gaussian_blur_axis(image, sigma, axis): ...
def bilinear_interpolate(image, new_height, new_width, align_corners: bool = False): ...
def resize_bilinear(image, new_size, align_corners: bool = False, antialias: bool = True): ...
