from ..base import BaseModelConfig as BaseModelConfig
from dataclasses import dataclass

@dataclass
class ModelConfig(BaseModelConfig):
    text_config: TextConfig
    vision_config: VisionConfig
    model_type: str
    ignore_index: int = ...
    vocab_size: int = ...
    scale_factor: int = ...
    media_placeholder_token_id: int = ...
    image_token_index: int | None = ...
    eos_token_id: list[int] | None = ...
    def __post_init__(self) -> None: ...

@dataclass
class TextConfig(BaseModelConfig):
    model_type: str = ...
    vocab_size: int = ...
    hidden_size: int = ...
    intermediate_size: int = ...
    moe_intermediate_size: int = ...
    num_hidden_layers: int = ...
    num_attention_heads: int = ...
    num_key_value_heads: int = ...
    n_shared_experts: int | None = ...
    n_routed_experts: int | None = ...
    routed_scaling_factor: float = ...
    kv_lora_rank: int = ...
    q_lora_rank: int = ...
    qk_rope_head_dim: int = ...
    v_head_dim: int = ...
    qk_nope_head_dim: int = ...
    topk_method: str = ...
    scoring_func: str = ...
    norm_topk_prob: bool = ...
    n_group: int | None = ...
    topk_group: int | None = ...
    num_experts_per_tok: int | None = ...
    moe_layer_freq: int = ...
    first_k_dense_replace: int = ...
    max_position_embeddings: int = ...
    rms_norm_eps: float = ...
    rope_theta: float = ...
    rope_scaling: dict = ...
    attention_bias: bool = ...
    def __post_init__(self) -> None: ...

@dataclass
class VisionConfig(BaseModelConfig):
    model_type: str = ...
    depth: int = ...
    embed_dim: int = ...
    hidden_size: int = ...
    num_heads: int = ...
    image_size: int = ...
    patch_size: int = ...
    vocab_size: int = ...
    mlp_ratio: float = ...
    num_channels: int = ...
    layer_norm_eps: float = ...
    intermediate_size: int = ...
    init_pos_emb_height: int = ...
    init_pos_emb_width: int = ...
    spatial_patch_size: int = ...
    spatial_merge_size: int = ...
    temporal_patch_size: int = ...
    merge_kernel_size: list[int, int] = ...
    def __post_init__(self) -> None: ...
